### ISSUE TITLE
Slow speech recognition

### ISSUE THREAD

**Issue by Acquil** [Acquil/deep-read#7]
![image](https://user-images.githubusercontent.com/34624268/94369440-52c56880-0107-11eb-9212-85810e87c488.png) 
for 7:03  video.
Referenced PRs
- #4 
- #3

**Comment by Acquil** [comment]
Takes around 30 sec to transcribe for 1 minute split in the audio file but a single 7 min chunk takes only 70 seconds, so larger chunks of audio are preferred. 

Additional stats to report:
**2 min 23 seconds** elapsed for **28 min video/audio**(split into 4 minute segments) with 8 subprocesses.

**Comment by Acquil** [comment]
### Additional Tasks:

- [ ] Benchmark with different options against different audio files.

- [ ] Check if words get cut out in the middle while dividing into chunks.
    - [ ] Might require changes in [audiosplitter.py](https://github.com/Acquil/deep-read/blob/speech_text/workbench/speech/audiosplitter.py)

### To test please do the following
1. Switch to speech_text branch 
2. Go to  deep-read/workbench/speech/  
3. Run setup.sh
`chmod +x setup.sh`
`./setup.sh`
4. Run speech.py and pass path to audio file as cmd-line argument.
`chmod +x speech.py`
`./speech.py input.wav`

You can convert a video to a .wav file with ffmpeg `ffmpeg -i input.mp4 -vn deep-read/workbench/speech/output.wav`

**Comment by harish-ganesh** [comment]
We will evaluate Speech Recognition with Indian(EN) model.
